        function HelpPropagation(~,~)
            Threshinfo = figure('color',[1 1 1],'Position',[150 75 800 800],'NumberTitle','off','toolbar','none','Name','Information about the module "Signal Propagation"');
            
            uicontrol('Parent',Threshinfo,'style','text','units','Pixels','position', [5 5 790 790],'backgroundcolor',[1 1 1],'FontSize',10,'HorizontalAlignment','left',...
                'String','This module serves the purpose of calculating the signal velocity on a manuelly defined path. The whole process consists of the following 3 steps:')
            
            uicontrol('Parent',Threshinfo,'style','text','units','Pixels','position', [5 5 790 750],'backgroundcolor',[1 1 1],'FontSize',10,'HorizontalAlignment','left',...
                'String','1. To make sure that the calculation of the signal propagation is done correctly, the Event-Array has to be filtered with "Event-Select".')
            
            uicontrol('Parent',Threshinfo,'style','text','units','Pixels','position', [5 5 790 720],'backgroundcolor',[1 1 1],'FontSize',10,'HorizontalAlignment','left',...
                'String','2. To be able to define a signal path in an event, one event has to be choosen in the popupmenu "Event". If an event has been selecte it will be drawn in the module and can be used for further processing.')
            
            uicontrol('Parent',Threshinfo,'style','text','units','Pixels','position', [5 5 790 670],'backgroundcolor',[1 1 1],'FontSize',10,'HorizontalAlignment','left',...
                'String','3. The definition of the signal path is done through the buttons "Start"/"Stop". "Start" activates the function which allows to select points within the drawn event from point 2. "Stop" ends the activated function and triggers the algorithm which draws the signal path and calculates the distance and time difference between the defined points. With the knowledge about distance and needed time the velocity can be calculated in a subsequent step.')
            
            uicontrol('Parent',Threshinfo,'style','text','units','Pixels','position', [5 5 790 590],'backgroundcolor',[1 1 1],'FontSize',10,'HorizontalAlignment','left',...
                'FontWeight','bold','string','Raster Plot');
            uicontrol('Parent',Threshinfo,'style','text','units','Pixels','position', [5 5 790 570],'backgroundcolor',[1 1 1],'FontSize',10,'HorizontalAlignment','left',...
                'String','As an additional tool to analyze the recognized spikes this function will creat a chart which shows the measurement time on the x-axis and the electrode numbers on the y-axis. Occuring spikes will be marked with "|" at the corresponding time as x value and electrode as y value.');
            
            uicontrol('Parent',Threshinfo,'style','text','units','Pixels','position', [5 5 790 510],'backgroundcolor',[1 1 1],'FontSize',10,'HorizontalAlignment','left',...
                'FontWeight','bold','string','Event Select');
            uicontrol('Parent',Threshinfo,'style','text','units','Pixels','position', [5 5 790 490],'backgroundcolor',[1 1 1],'FontSize',10,'HorizontalAlignment','left',...
                'String','The two panels which will open when this function is activated serve as means to filter the events inside the Event-Matrix. This is achieved through two different ways. The first one allows to address a specific event through a popupmenu which contains the corresponding event numbers. If one number has been selected the associated event can be removed from the matrix via the button "Remove Num". The second way uses the checkboxes in the second overview panel. Events can be removed by checking the appendant boxes and pressing the button "remove check".');
            
            uicontrol('Parent',Threshinfo,'style','text','units','Pixels','position', [5 5 790 400],'backgroundcolor',[1 1 1],'FontSize',10,'HorizontalAlignment','left',...
                'FontWeight','bold','string','3D');
            uicontrol('Parent',Threshinfo,'style','text','units','Pixels','position', [5 5 790 380],'backgroundcolor',[1 1 1],'FontSize',10,'HorizontalAlignment','left',...
                'String','This function creates an additional figure which shows the three dimenisonal view of the selected Event in the popupmenu "Event".');
            
            uicontrol('Parent',Threshinfo,'style','text','units','Pixels','position', [5 5 790 350],'backgroundcolor',[1 1 1],'FontSize',10,'HorizontalAlignment','left',...
                'FontWeight','bold','string','Video');
            uicontrol('Parent',Threshinfo,'style','text','units','Pixels','position', [5 5 790 330],'backgroundcolor',[1 1 1],'FontSize',10,'HorizontalAlignment','left',...
                'String','The function "Video" allows to create a .avi movie of an event. By pressing the button "Video" a processing panel with the button "save under" will be created. With the activation of "save under" a browser panel will open up which allows to define the storage location of the movie. If the location is confirmed the function will start to creat and then save the .avi File.');
            
            uicontrol('Parent',Threshinfo,'style','text','units','Pixels','position', [5 5 790 270],'backgroundcolor',[1 1 1],'FontSize',10,'HorizontalAlignment','left',...
                'FontWeight','bold','string','Contour Lines');
            uicontrol('Parent',Threshinfo,'style','text','units','Pixels','position', [5 5 790 250],'backgroundcolor',[1 1 1],'FontSize',10,'HorizontalAlignment','left',...
                'String','An additional feature of the visualization is the possibility to draw contour lines inside the choosen event. The density of the lines can be changed through the nearby popupmenu');
            
            uicontrol('Parent',Threshinfo,'style','text','units','Pixels','position', [5 5 790 210],'backgroundcolor',[1 1 1],'FontSize',10,'HorizontalAlignment','left',...
                'FontWeight','bold','string','Velocity Vector');
            uicontrol('Parent',Threshinfo,'style','text','units','Pixels','position', [5 5 790 190],'backgroundcolor',[1 1 1],'FontSize',10,'HorizontalAlignment','left',...
                'String','This function serves as a mean to visualize the propagation course of the signal wave through velocity vectors that. The x- and y-value of the vector describe the dircetion of the signal while the magnitude of the vector describes the velocity of the signal wave.');
        end%~~